#ifndef LAHJOITUSDLL_GLOBAL_H
#define LAHJOITUSDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LAHJOITUSDLL_LIBRARY)
#  define LAHJOITUSDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LAHJOITUSDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LAHJOITUSDLL_GLOBAL_H
